default["git"]["version"] = "v1.8.4"
default["zsh"]["version"] = "zsh-5.0.2"
default["vim"]["version"] = "v7-4"
default["hg"]["install_method"] = "package"
default["libevent"]["version"] = "release-2.0.21-stable"
default["tmux"]["version"] = "1.8"
